name: Build Frontend (main, stage-test & stage-prod)

on:
  push:
    branches: [ main, stage-test, stage-prod ]
    paths:
      - 'frontend/**'
      - '.github/workflows/build-frontend.yml'

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm install
    - run: npm run build
    - run: npm test
    - run: mv dist/mempool/browser/en-US/* dist/mempool/browser
    - name: Deploy Frontend to `haushoppe/ordpool-build` repo
      if: ${{ github.ref_name != 'main' }}
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npx angular-cli-ghpages --repo=https://github.com/haushoppe/ordpool-build.git --branch=$GITHUB_REF_NAME --dir=dist/mempool/browser --name="The Buildbot" --email=noreply@haushoppe.art --no-notfound --no-nojekyll
